version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: rozkaana
      POSTGRES_USER: rozkaana
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  app:
    build: .
    environment:
      - DATABASE_URL=postgresql+asyncpg://rozkaana:pass@postgres/rozkaana
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery_worker:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A app.tasks.celery_app worker --loglevel=info

  celery_beat:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A app.tasks.celery_app beat --loglevel=info

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  landing-page:
    image: nginx:alpine
    ports:
      - "7070:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: