"""initial_schema

Revision ID: 6c7fce8eaf9b
Revises: 
Create Date: 2026-04-26 16:08:43.606489+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c7fce8eaf9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create households WITHOUT the FK to users (circular dep: users → households → users)
    op.create_table('households',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head_user_id', sa.UUID(), nullable=True),
    sa.Column('shared_eating_mode', sa.String(length=20), nullable=True),
    sa.Column('member_count', sa.SmallInteger(), server_default='1', nullable=True),
    sa.Column('cuisine_prefs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_sessions_phone'), 'otp_sessions', ['phone'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_local', sa.String(length=200), nullable=True),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('cuisine_region', sa.String(length=30), nullable=False),
    sa.Column('eating_mode_tags', sa.ARRAY(sa.String()), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('health_safe_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('allergy_free_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('calories', sa.SmallInteger(), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fibre_g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('serving_unit', sa.String(length=50), nullable=True),
    sa.Column('prep_time_mins', sa.SmallInteger(), nullable=True),
    sa.Column('spice_level', sa.String(length=10), nullable=True),
    sa.Column('main_ingredient', sa.String(length=50), nullable=True),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steps', sa.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipes_allergy_free_tags', 'recipes', ['allergy_free_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_recipes_cuisine_region'), 'recipes', ['cuisine_region'], unique=False)
    op.create_index('ix_recipes_eating_mode_tags', 'recipes', ['eating_mode_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_recipes_health_safe_tags', 'recipes', ['health_safe_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_recipes_is_verified'), 'recipes', ['is_verified'], unique=False)
    op.create_index(op.f('ix_recipes_meal_type'), 'recipes', ['meal_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('bmi_band', sa.String(length=20), nullable=True),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('eating_mode', sa.String(length=20), nullable=True),
    sa.Column('nv_days', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('health_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('allergy_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('cuisine_prefs', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('daily_calorie_target', sa.SmallInteger(), nullable=True),
    sa.Column('daily_protein_target_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('daily_carbs_target_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('daily_fat_target_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('is_household_head', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('wa_phone', sa.String(length=15), nullable=True),
    sa.Column('wa_opted_in', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_allergy_tags', 'users', ['allergy_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_health_tags', 'users', ['health_tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # Now add the deferred FK from households → users
    op.create_foreign_key('fk_households_head_user_id', 'households', 'users', ['head_user_id'], ['id'])
    op.create_table('daily_menus',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.Column('menu_date', sa.Date(), nullable=False),
    sa.Column('breakfast_id', sa.UUID(), nullable=True),
    sa.Column('morning_snack_id', sa.UUID(), nullable=True),
    sa.Column('lunch_id', sa.UUID(), nullable=True),
    sa.Column('evening_snack_id', sa.UUID(), nullable=True),
    sa.Column('dinner_id', sa.UUID(), nullable=True),
    sa.Column('total_calories', sa.SmallInteger(), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cuisine_override', sa.String(length=30), nullable=True),
    sa.Column('is_regenerated', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('pdf_key', sa.String(length=300), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('wa_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wa_status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['breakfast_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['dinner_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['evening_snack_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['lunch_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['morning_snack_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'owner_type', 'menu_date', name='uq_daily_menu_owner_date')
    )
    op.create_index(op.f('ix_daily_menus_menu_date'), 'daily_menus', ['menu_date'], unique=False)
    op.create_index(op.f('ix_daily_menus_owner_id'), 'daily_menus', ['owner_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_start', sa.Date(), nullable=True),
    sa.Column('trial_end', sa.Date(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('rzp_subscription_id', sa.String(length=50), nullable=True),
    sa.Column('rzp_customer_id', sa.String(length=50), nullable=True),
    sa.Column('rzp_plan_id', sa.String(length=50), nullable=True),
    sa.Column('paused_at', sa.Date(), nullable=True),
    sa.Column('pause_days_used', sa.SmallInteger(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_households_head_user_id', 'households', type_='foreignkey')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_daily_menus_owner_id'), table_name='daily_menus')
    op.drop_index(op.f('ix_daily_menus_menu_date'), table_name='daily_menus')
    op.drop_table('daily_menus')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index('ix_users_health_tags', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_allergy_tags', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_index(op.f('ix_recipes_meal_type'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_is_verified'), table_name='recipes')
    op.drop_index('ix_recipes_health_safe_tags', table_name='recipes', postgresql_using='gin')
    op.drop_index('ix_recipes_eating_mode_tags', table_name='recipes', postgresql_using='gin')
    op.drop_index(op.f('ix_recipes_cuisine_region'), table_name='recipes')
    op.drop_index('ix_recipes_allergy_free_tags', table_name='recipes', postgresql_using='gin')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_otp_sessions_phone'), table_name='otp_sessions')
    op.drop_table('otp_sessions')
    op.drop_table('households')
    # ### end Alembic commands ###
